//go:build !ignore_autogenerated

/*
Copyright 2024 The Service Weighted CRD Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceWeight) DeepCopyInto(out *ServiceWeight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceWeight.
func (in *ServiceWeight) DeepCopy() *ServiceWeight {
	if in == nil {
		return nil
	}
	out := new(ServiceWeight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceWeightList) DeepCopyInto(out *ServiceWeightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceWeight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceWeightList.
func (in *ServiceWeightList) DeepCopy() *ServiceWeightList {
	if in == nil {
		return nil
	}
	out := new(ServiceWeightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceWeightSpec) DeepCopyInto(out *ServiceWeightSpec) {
	*out = *in
	in.ServiceSpec.DeepCopyInto(&out.ServiceSpec)
	if in.WeightedBackends != nil {
		in, out := &in.WeightedBackends, &out.WeightedBackends
		*out = make([]WeightedBackend, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceWeightSpec.
func (in *ServiceWeightSpec) DeepCopy() *ServiceWeightSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceWeightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceWeightStatus) DeepCopyInto(out *ServiceWeightStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceWeightStatus.
func (in *ServiceWeightStatus) DeepCopy() *ServiceWeightStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceWeightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightedBackend) DeepCopyInto(out *WeightedBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightedBackend.
func (in *WeightedBackend) DeepCopy() *WeightedBackend {
	if in == nil {
		return nil
	}
	out := new(WeightedBackend)
	in.DeepCopyInto(out)
	return out
}
